### PR TITLE
Migrate to Go Modules

### LINKED ISSUE #551: Migrate to go modules
Description
===========
Following the 1.9 deprecation in #548 a step forward to be better compatible is to migrate to go modules:
1. Migrate to go modules including examples + kafkatest
2. Some code us gopkg.in and some use another, deprecate all usages of gopkg.in  
3. Update documentation

### PR DESCRIPTION
**Pull request by eran-levy**
fixes #551

### CODE REVIEW

**Comment by jeffwidman** [comment]
@edenhill what's holding this up? Is it just the CLA / merge conflicts? Happy to help with whatever is needed to push this across the line, as it'd make life easier.

**Comment by eran-levy** [comment]
I will be very happy to move it forward in case we get a greenlight just to rebasr and fix

**Comment by edenhill** [comment]
Can you rebase this off latest master and sign the CLA and we'll try to get it in the upcoming 1.9.0 release?

**Comment by eran-levy** [comment]
Yes np @edenhill I will do it

**Comment by eran-levy** [comment]
@edenhill @jeffwidman I had issues with CLA and the commit from 2 years ago which had to ammend for author. 
Created a new clean branch with new PR to resolve it - see PR #760

**Pull request closed without merging**
