### PR TITLE
Move testhelpers' code to _test.go file

### LINKED ISSUE #1048: 'testing' is imported in non-test files (testhelpers.go)
Description
===========
The file 'testhelpers.go' is adding test code to production builds. That file contains 'testing' package and adds some flags that appear in the usage of the final program. This bug is a regression of #51 but with a different set of flags.

How to reproduce
================
Given the following code, obtained from #51 and updated to the latest version of confluent-kafka-go:
```
package main

import (
	"flag"

	"github.com/confluentinc/confluent-kafka-go/v2/kafka"
)

func main() {
	flag.Parse()
	kafka.NewProducer(&kafka.ConfigMap{"bootstrap.servers": "foo"})
}
```

we get the following help output:

```
$ ./foo --help
Usage of ./main:
  -clients.docker
    	Decides whether a docker container be brought up automatically
  -clients.semaphore
    	Tells if the job is running on Semaphore
```

Checklist
=========
Please provide the following information:

 - [X] confluent-kafka-go and librdkafka version (`LibraryVersion()`):  v2.2.0 and librdkafka-static-bundle-v2.2.0.tgz
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [X] Operating system:  linux  (glibc and musl)
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

### PR DESCRIPTION
**Pull request by dmlambea**
Fixes #1048

### CODE REVIEW

**Comment by milindl** [comment]
Thanks for this change @dmlambea 
Could you sign the CLA for this change, I'll run it on an internal CI branch to merge it.

**Comment by dmlambea** [comment]
> Thanks for this change @dmlambea Could you sign the CLA for this change, I'll run it on an internal CI branch to merge it.

I've done it already. It seem the "CLA not signed yet" comment has been registered after the "CLA signed" one.

**Comment by milindl** [comment]
Right @dmlambea , I think the CLA signatures got reset for some reason for all the contributors at once. Could you retry signing it once, if that works? Thanks

**Comment by dmlambea** [comment]
> Right @dmlambea , I think the CLA signatures got reset for some reason for all the contributors at once. Could you retry signing it once, if that works? Thanks

I've retried a minute ago with success. cla-assistant.io says:  "You have agreed to the CLA for confluentinc/confluent-kafka-go"  and below there is the version of the CLA (2023-08-04) along with the complete text and my personal data.

**Comment by milindl** [comment]
Thank you. I created the internal branch and raised a PR with that so the CI can run. #1077

**Comment by milindl** [comment]
Merged the internal branch after CI checks.
Thanks for the issue and the PR @dmlambea !

**Pull request closed without merging**
