### PR TITLE
Added rd_kafka_list_groups API to get consumer group subscription metadata

### PR DESCRIPTION
**Pull request by simnotes**
I added new GetConsumerGroupsMetadata function to consumer, producer and adminClient API, which calls rd_kafka_list_groups from librdkafka to retrieve current consumer group status and consumer group subscriptions from broker. Via the new API it is possible to query subscription-status like in "kafka-consumer-groups.sh"

Also added integration and dry-tests to everything.

### CODE REVIEW

**Comment by edenhill** [comment]
Thank you! Will review this as soon as v1.0.0 is out (a couple of weeks)

**Comment by edenhill** [comment]
Thank you! Will review this as soon as v1.0.0 is out (a couple of weeks)

**Comment by ruseinov** [comment]
@edenhill Any idea if this ever gets merged into master? Looking for a similar functionality to support dynamic kafka monitoring for all the consumers

**Comment by ruseinov** [comment]
@edenhill Any idea if this ever gets merged into master? Looking for a similar functionality to support dynamic kafka monitoring for all the consumers and this would be a lot of help.

**Comment by kimba74** [comment]
@edenhill I second @ruseinov. I'm as well looking for the possibility of dynamic Kafka monitoring and this would be **very** helpful indeed.

**Comment by sourcec0de** [comment]
@edenhill my team is also looking for this functionality.
Confluent Cloud doesn't make this information available from its metrics API.
This feature seems high value.

**Pull request closed without merging**
