### PR TITLE
updated go version to 1.21 and testcontainers-go dependency to v0.29.1

### PR DESCRIPTION
**Pull request by rzeijde**

### CODE REVIEW

**Comment by milindl** [comment]
Thank you. Approving to run CI.

**Review by milindl — DISMISSED** [review]

**Review by milindl — APPROVED** [review]

**Review by emasab — APPROVED** [review]
LGTM thanks

**Comment by milindl** [comment]
Thanks @rzeijde , and thanks @emasab for the review

**Pull request merged**
