### PR TITLE
Add missing API parts for schema registry

### PR DESCRIPTION
**Pull request by oleksandrkorzhenevskyi**
this are the changes from #1187 with the merged master on top

### CODE REVIEW

**Comment by oleksandrkorzhenevskyi** [comment]
@rayokota please, take a look at this PR. This is SAP-related.

**Comment by oleksandrkorzhenevskyi** [comment]
I am not sure what to do with api.html.

**Review by rayokota — APPROVED** [review]
Thanks @oleksandrkorzhenevskyi, LGTM

**Review by yao-gu — APPROVED** [review]
LGTM

**Pull request merged**
