### PR TITLE
Import Windows Build of v1.5.0

### LINKED ISSUE #501: Create kafka\build_windows.go and kafka\librdkafka\librdkafka_windows.a
Description
===========
librdkafka v1.5.0 is released, and supports MinGW builds (see https://github.com/edenhill/librdkafka/tree/master/packaging/mingw-w64). Since MinGW is the only compiler toolchain we can expect Windows Go programmers to be using, we should include static builds with confluent-kafka-go. This would effectively add Windows support to this library and avoid the need for us to use workarounds like those described in https://github.com/confluentinc/confluent-kafka-go/issues/128

Checklist
=========
Please provide the following information:

 - [X] confluent-kafka-go and librdkafka version (`LibraryVersion()`): v1.5.0
 - [X] Operating system: Windows

### PR DESCRIPTION
**Pull request by neptoess**
Added scripts (`bundle-windows.cmd`, `bundle-windows.sh`) and artifacts for Windows static library. Resolves #501

### CODE REVIEW

**Comment by neptoess** [comment]
[clabot:check]

**Comment by neptoess** [comment]
There will be some dependencies outside of the static librdkafka. @edenhill , I can't seem to find where you communicate these to the end user for macOS or Linux. Are the linker errors sufficient?

```
$ ntldd hello.exe
        libcrypto-1_1-x64.dll => C:\msys64\mingw64\bin\libcrypto-1_1-x64.dll (0x0000000003250000)
        liblz4.dll => C:\msys64\mingw64\bin\liblz4.dll (0x0000000000790000)
        libssl-1_1-x64.dll => C:\msys64\mingw64\bin\libssl-1_1-x64.dll (0x00000000029b0000)
        libzstd.dll => C:\msys64\mingw64\bin\libzstd.dll (0x00000000029b0000)
        CRYPT32.dll => C:\WINDOWS\SYSTEM32\CRYPT32.dll (0x0000000003760000)
        KERNEL32.dll => C:\WINDOWS\SYSTEM32\KERNEL32.dll (0x0000000002a50000)
        msvcrt.dll => C:\WINDOWS\SYSTEM32\msvcrt.dll (0x0000000002a50000)
        libwinpthread-1.dll => C:\msys64\mingw64\bin\libwinpthread-1.dll (0x00000000001d0000)
        Secur32.dll => C:\WINDOWS\SYSTEM32\Secur32.dll (0x00000000001d0000)
        WS2_32.dll => C:\WINDOWS\SYSTEM32\WS2_32.dll (0x0000000003810000)
```

**Comment by edenhill** [comment]
@neptoess There are no external dependencies on Linux and OSX and having to install external dependencies sort of defeats the purpose of bundling librdkafka.
I wonder if we can do the same thing as on Linux and OSX where we combine all dependencies and librdkafka into one static lib.

**Comment by neptoess** [comment]
@edenhill I was pursuing this, but it looks a little tricky. No matter what build/linker flags I pass, I end up with the just the rdkafka files in the .a (since we aren’t building an executable, the linker doesn’t really _link_ it seems). Looks like we need to manually bundle all the .o files ourselves. It doesn’t solve for header files though, e.g. openssl.

**Comment by neptoess** [comment]
Alright. Newest push removes any static linking requirements. Only downside is I had to remove SASL support, since the package doesn't ship with a static build.
```
ntldd .\hello.exe
        ADVAPI32.dll => C:\WINDOWS\SYSTEM32\ADVAPI32.dll (0x0000000001bb0000)
        CRYPT32.dll => C:\WINDOWS\SYSTEM32\CRYPT32.dll (0x0000000001d60000)
        KERNEL32.dll => C:\WINDOWS\SYSTEM32\KERNEL32.dll (0x0000000001c50000)
        msvcrt.dll => C:\WINDOWS\SYSTEM32\msvcrt.dll (0x0000000001c50000)
        libwinpthread-1.dll => C:\msys64\mingw64\bin\libwinpthread-1.dll (0x0000000000020000)
        Secur32.dll => C:\WINDOWS\SYSTEM32\Secur32.dll (0x0000000000020000)
        USER32.dll => C:\WINDOWS\SYSTEM32\USER32.dll (0x0000000001c50000)
        WS2_32.dll => C:\WINDOWS\SYSTEM32\WS2_32.dll (0x0000000000df0000)
```

**Comment by edenhill** [comment]
@neptoess Great stuff!
What SASL support did you need to delete?
Can you provide the ./configure output as well as the `builtin.features` from e.g `rdkafka_example -X builtin.features`?

**Comment by neptoess** [comment]
@edenhill 
I passed `WITH_SASL=OFF` to cmake, as the MSYS2 package `mingw-w64-x86_64-cyrus-sasl`, which is the only 64-bit MinGW package providing <sasl/sasl.h>, only ships with DLLs, these ones in particular
```
$ pacman -Fl mingw-w64-x86_64-cyrus-sasl | grep -e "[.]a$"
mingw-w64-x86_64-cyrus-sasl mingw64/lib/libsasl2.dll.a
mingw-w64-x86_64-cyrus-sasl mingw64/lib/sasl2/libanonymous.dll.a
mingw-w64-x86_64-cyrus-sasl mingw64/lib/sasl2/libcrammd5.dll.a
mingw-w64-x86_64-cyrus-sasl mingw64/lib/sasl2/libdigestmd5.dll.a
mingw-w64-x86_64-cyrus-sasl mingw64/lib/sasl2/libotp.dll.a
mingw-w64-x86_64-cyrus-sasl mingw64/lib/sasl2/libplain.dll.a
mingw-w64-x86_64-cyrus-sasl mingw64/lib/sasl2/libsasldb.dll.a
mingw-w64-x86_64-cyrus-sasl mingw64/lib/sasl2/libscram.dll.a

$ pacman -Fl mingw-w64-x86_64-cyrus-sasl | grep -e "/bin/"
mingw-w64-x86_64-cyrus-sasl mingw64/bin/
mingw-w64-x86_64-cyrus-sasl mingw64/bin/libsasl2-3.dll
```

I'm using cmake, not autotools, so I attached the entire output of the `bundle-windows.sh` script
[bundle-windows.log](https://github.com/confluentinc/confluent-kafka-go/files/5169115/bundle-windows.log)

Also, I don't think `rdkafka_example` builds under Windows, so I threw this quick and dirty `conf_dump.c` together
```
#include "../src/rdkafka.h"

int main(void)
{
	rd_kafka_conf_t *conf = rd_kafka_conf_new();
	char dest[512];
	size_t dest_size = sizeof(dest);
	rd_kafka_conf_get(conf, "builtin.features", dest, &dest_size);
	printf("%s\n", dest);
	
	return 0;
}
```

Build and output
```
$ gcc conf_dump.c /c/Users/neptoess/go/src/github.com/neptoess/confluent-kafka-go/kafka/librdkafka/librdkafka_windows.a -DLIBRDKAFKA_STATICLIB -lws2_32 -lsecur32 -lcrypt32                     

$ ./a.exe
ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,zstd
```

Kinda weird that we're seeing sasl in there despite passing `WITH_SASL=OFF`. Either way, looking back at my previous `ntldd` output (https://github.com/confluentinc/confluent-kafka-go/pull/509#issuecomment-686241108), it looks like, even when I was passing `-lsasl2` in `LDFLAGS`, there was no dependency on the sasl DLL. The librdkafka.dll in the librdkafka.redist v1.5.0 NuGet package also has no sasl DLL dependency for the win-x64 runtime. I'll dig into the rdkafka code and figure out what's going on.

**Comment by neptoess** [comment]
@edenhill I think this is ready to go now. No dynamic linking dependencies, `builtin.features` is `ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,zstd`.

**Comment by neptoess** [comment]
Going to try for #555 instead

**Pull request closed without merging**
